![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
!pip install numpy

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
import numpy as np

my_array = np.array(np.arange(0,10))
my_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [5]:
my_matrix33 = np.full((3, 3), True)
my_matrix33


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [25]:
my_array_impar = my_array[1::2].copy()
print(my_array)
print(my_array_impar)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [7]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [8]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [9]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [10]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [12]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [13]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [14]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [15]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [16]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [17]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 16
Lee la imagen "numpy.png"

In [18]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [19]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [20]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [21]:
# AQUÍ VA VUESTRO CÓDIGO

## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [22]:
# AQUÍ VA VUESTRO CÓDIGO